#!/bin/bash

thetvdbToken=""

while [[ $# -gt 1 ]]
do
key="$1"
case $key in
    -t|--token)
    thetvdbToken="$2"
    shift
    ;;
esac
shift # past argument or value
done

if [ -z $thetvdbToken ]; then
    thetvdbToken=$(./thetvdb-login | jq -r .token)

    echo Using token: "$thetvdbToken"
fi

series=$1

url="https://api.thetvdb.com/search/series"

curl -G -X GET -H "Authorization: Bearer $thetvdbToken" \
               -H "Accept: application/json" \
               --data-urlencode "name=$series" \
               "$url"
